package haproxy

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"time"

	"transitforge/internal/cmdexec"
	"transitforge/internal/model"
	"transitforge/internal/reconcile"
	"transitforge/internal/validate"
)

const (
	BeginMarker = "# BEGIN TRANSITFORGE MANAGED"
	EndMarker   = "# END TRANSITFORGE MANAGED"
	// Pre-rebrand HAProxy markers. Read on discover; new writes use BeginMarker/EndMarker.
	legacyBeginMarker = "# BEGIN PROXYCTL MANAGED"
	legacyEndMarker   = "# END PROXYCTL MANAGED"
)

type Manager struct {
	Runner     cmdexec.CommandRunner
	ConfigPath string
	BackupDir  string
	UnitName   string
	// ReloadMode is "systemctl" (default) or "external".
	// external writes and validates the config but does not call systemctl —
	// a host path unit / watcher must reload HAProxy.
	ReloadMode string

	mu         sync.Mutex
	lastBackup string
	wroteOnce  bool
}

func (m *Manager) skipSystemctl() bool {
	switch strings.ToLower(strings.TrimSpace(m.ReloadMode)) {
	case "external", "skip":
		return true
	default:
		return false
	}
}

func (m *Manager) unit() string {
	if m.UnitName == "" {
		return "haproxy"
	}
	return m.UnitName
}

func (m *Manager) Discover(ctx context.Context, desired []model.SniRoute) (digest string, routes []model.SniRoute, conflicts []model.Conflict, err error) {
	body, err := os.ReadFile(m.ConfigPath)
	if err != nil {
		if os.IsNotExist(err) {
			return "", nil, nil, nil
		}
		return "", nil, nil, err
	}
	unmanaged, managed, err := splitManaged(string(body))
	if err != nil {
		return "", nil, []model.Conflict{{Code: "HAPROXY_MARKERS", Target: m.ConfigPath, Message: err.Error()}}, nil
	}
	if portBoundElsewhere(unmanaged, desired) {
		conflicts = append(conflicts, model.Conflict{
			Code:    "HAPROXY_BIND_COLLISION",
			Target:  m.ConfigPath,
			Message: "unmanaged HAProxy config already binds a listen address managed by transitforge",
		})
	}
	routes = parseManaged(managed)
	digest = parseDigestComment(managed)
	if digest == "" && managed != "" {
		digest = reconcile.SniDigest(routes)
	}
	_ = ctx
	return digest, routes, conflicts, nil
}

func (m *Manager) Apply(ctx context.Context, routes []model.SniRoute, backends []model.Backend) error {
	m.mu.Lock()
	defer m.mu.Unlock()
	for _, r := range routes {
		if err := r.Validate(); err != nil {
			return err
		}
		if err := validate.ListenAddr(r.Listen); err != nil {
			return err
		}
	}
	current, err := readOrEmpty(m.ConfigPath)
	if err != nil {
		return err
	}
	unmanaged, _, err := splitManaged(current)
	if err != nil {
		return model.ErrConflict(err.Error())
	}
	if portBoundElsewhere(unmanaged, routes) {
		return model.ErrConflict("unmanaged HAProxy section already binds a transitforge listen address")
	}
	rendered, err := Render(routes, backends)
	if err != nil {
		return err
	}
	next := joinConfig(unmanaged, rendered)
	backup, err := m.backup(current)
	if err != nil {
		return err
	}
	m.lastBackup = backup
	if err := writeFileAtomic(m.ConfigPath, []byte(next), 0o640); err != nil {
		return err
	}
	m.wroteOnce = true
	if _, errb, err := m.Runner.Run(ctx, "haproxy", "-c", "-f", m.ConfigPath); err != nil {
		_ = restoreFile(m.ConfigPath, current)
		return model.ErrConflict(fmt.Sprintf("haproxy validation failed: %v (%s)", err, strings.TrimSpace(string(errb))))
	}
	if err := m.reload(ctx); err != nil {
		_ = restoreFile(m.ConfigPath, current)
		_ = m.reload(ctx)
		return model.ErrConflict(fmt.Sprintf("haproxy reload failed, config restored: %v", err))
	}
	return nil
}

func (m *Manager) reload(ctx context.Context) error {
	if m.skipSystemctl() {
		return nil
	}
	_, errb, err := m.Runner.Run(ctx, "systemctl", "reload", m.unit())
	if err != nil {
		return fmt.Errorf("%v (%s)", err, strings.TrimSpace(string(errb)))
	}
	return nil
}

func (m *Manager) Rollback(ctx context.Context) error {
	m.mu.Lock()
	defer m.mu.Unlock()
	if m.lastBackup == "" {
		return nil
	}
	b, err := os.ReadFile(m.lastBackup)
	if err != nil {
		return err
	}
	if err := restoreFile(m.ConfigPath, string(b)); err != nil {
		return err
	}
	if err := m.reload(ctx); err != nil {
		return fmt.Errorf("haproxy rollback reload: %w", err)
	}
	return nil
}

func (m *Manager) backup(current string) (string, error) {
	if m.BackupDir == "" {
		m.BackupDir = filepath.Join(filepath.Dir(m.ConfigPath), "transitforge-haproxy-backups")
	}
	if err := os.MkdirAll(m.BackupDir, 0o750); err != nil {
		return "", err
	}
	name := filepath.Join(m.BackupDir, "haproxy-"+time.Now().UTC().Format("20060102T150405.000Z")+".cfg")
	if err := os.WriteFile(name, []byte(current), 0o640); err != nil {
		return "", err
	}
	return name, nil
}

func Render(routes []model.SniRoute, backends []model.Backend) (string, error) {
	if len(routes) == 0 {
		return "", nil
	}
	byID := map[model.ID]model.Backend{}
	byName := map[string]model.Backend{}
	for _, b := range backends {
		byID[b.ID] = b
		byName[b.Name] = b
	}
	var b strings.Builder
	b.WriteString(BeginMarker + "\n")
	b.WriteString("# Generated by transitforge. Do not edit this block.\n")
	fmt.Fprintf(&b, "# transitforge-sni-digest: %s\n", reconcile.SniDigest(routes))
	for _, r := range routes {
		front := fmt.Sprintf("transitforge_fe_%s", sanitize(string(r.ID)))
		if r.ID == "" {
			front = "transitforge_fe_" + sanitize(r.Listen)
		}
		fmt.Fprintf(&b, "frontend %s\n", front)
		fmt.Fprintf(&b, "    bind %s\n", r.Listen)
		b.WriteString("    mode tcp\n")
		b.WriteString("    tcp-request inspect-delay 5s\n")
		b.WriteString("    tcp-request content accept if { req_ssl_hello_type 1 }\n")
		var defName string
		for i, m := range r.Matches {
			be, err := resolveBackend(m, byID, byName)
			if err != nil {
				return "", err
			}
			beName := fmt.Sprintf("transitforge_be_%s_%d", sanitize(string(r.ID)), i)
			if m.Default {
				defName = beName
			} else {
				fmt.Fprintf(&b, "    use_backend %s if { req_ssl_sni -i %s }\n", beName, m.Match)
			}
			_ = be
		}
		if defName == "" {
			return "", model.Validation("sni route missing default backend")
		}
		fmt.Fprintf(&b, "    default_backend %s\n\n", defName)
		for i, m := range r.Matches {
			be, err := resolveBackend(m, byID, byName)
			if err != nil {
				return "", err
			}
			beName := fmt.Sprintf("transitforge_be_%s_%d", sanitize(string(r.ID)), i)
			port := 443
			fmt.Fprintf(&b, "backend %s\n", beName)
			b.WriteString("    mode tcp\n")
			fmt.Fprintf(&b, "    server s1 %s:%d\n\n", be.Address, port)
		}
	}
	b.WriteString(EndMarker + "\n")
	return b.String(), nil
}

func resolveBackend(m model.SniMatch, byID map[model.ID]model.Backend, byName map[string]model.Backend) (model.Backend, error) {
	if m.BackendID != "" {
		if b, ok := byID[m.BackendID]; ok {
			return b, nil
		}
	}
	if m.Backend != "" {
		if b, ok := byName[m.Backend]; ok {
			return b, nil
		}
	}
	return model.Backend{}, model.Validation("sni match references unknown backend")
}

func splitManaged(body string) (unmanaged, managed string, err error) {
	unmanaged, managed, err = splitMarked(body, BeginMarker, EndMarker)
	if err != nil || managed != "" || strings.Contains(body, BeginMarker) || strings.Contains(body, EndMarker) {
		return unmanaged, managed, err
	}
	return splitMarked(body, legacyBeginMarker, legacyEndMarker)
}

func splitMarked(body, beginMark, endMark string) (unmanaged, managed string, err error) {
	begin := strings.Index(body, beginMark)
	end := strings.Index(body, endMark)
	if begin < 0 && end < 0 {
		return body, "", nil
	}
	if begin < 0 || end < 0 || end < begin {
		return "", "", fmt.Errorf("mismatched %s / %s markers", beginMark, endMark)
	}
	unmanaged = strings.TrimSpace(body[:begin] + body[end+len(endMark):])
	managed = strings.TrimSpace(body[begin : end+len(endMark)])
	if strings.Count(body, beginMark) != 1 || strings.Count(body, endMark) != 1 {
		return "", "", fmt.Errorf("duplicate TransitForge HAProxy markers")
	}
	return unmanaged, managed, nil
}

func joinConfig(unmanaged, managed string) string {
	u := strings.TrimRight(unmanaged, "\n")
	m := strings.TrimLeft(managed, "\n")
	if u == "" {
		return m
	}
	if m == "" {
		return u + "\n"
	}
	return u + "\n\n" + m
}

func parseManaged(managed string) []model.SniRoute {
	if managed == "" {
		return nil
	}
	var routes []model.SniRoute
	var cur *model.SniRoute
	for _, line := range strings.Split(managed, "\n") {
		fs := strings.Fields(strings.TrimSpace(line))
		if len(fs) == 0 {
			continue
		}
		switch fs[0] {
		case "frontend":
			r := model.SniRoute{ID: model.ID(trimFrontendName(fs[1]))}
			routes = append(routes, r)
			cur = &routes[len(routes)-1]
		case "bind":
			if cur != nil && len(fs) > 1 {
				cur.Listen = fs[1]
			}
		case "use_backend":
			if cur != nil && len(fs) >= 8 {
				host := fs[len(fs)-1]
				host = strings.TrimRight(host, "}")
				cur.Matches = append(cur.Matches, model.SniMatch{Match: host, Backend: fs[1]})
			}
		case "default_backend":
			if cur != nil && len(fs) > 1 {
				cur.Matches = append(cur.Matches, model.SniMatch{Default: true, Backend: fs[1]})
			}
		}
	}
	return routes
}

func portBoundElsewhere(unmanaged string, routes []model.SniRoute) bool {
	low := strings.ToLower(unmanaged)
	for _, r := range routes {
		if r.Listen == "" {
			continue
		}
		if strings.Contains(low, "bind "+strings.ToLower(r.Listen)) {
			return true
		}
	}
	return false
}

func readOrEmpty(path string) (string, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return "", nil
		}
		return "", err
	}
	return string(b), nil
}

func restoreFile(path, body string) error {
	if body == "" {
		if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
			return err
		}
		return nil
	}
	return writeFileAtomic(path, []byte(body), 0o640)
}

func writeFileAtomic(path string, body []byte, mode os.FileMode) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
		return err
	}
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, body, mode); err != nil {
		return err
	}
	return os.Rename(tmp, path)
}

func sanitize(s string) string {
	s = strings.Map(func(r rune) rune {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '_' || r == '-' {
			return r
		}
		return '_'
	}, s)
	if s == "" {
		return "x"
	}
	return s
}

func parseDigestComment(managed string) string {
	for _, line := range strings.Split(managed, "\n") {
		line = strings.TrimSpace(line)
		for _, p := range []string{"# transitforge-sni-digest:", "# proxyctl-sni-digest:"} {
			if strings.HasPrefix(line, p) {
				return strings.TrimSpace(strings.TrimPrefix(line, p))
			}
		}
	}
	return ""
}

func trimFrontendName(name string) string {
	name = strings.TrimPrefix(name, "transitforge_fe_")
	return strings.TrimPrefix(name, "proxyctl_fe_")
}
